name = "REX 2024"
rename_dormcon_to = "Campus Wide!"

[orientation]
mandatory_tag = "BLACKOUT"
filename = "orientation.csv"
include_in_booklet = false

[csv]
# String format used for parsing dates in the CSV, see strftime.net
date_format = "%m/%d/%Y %H:%M"

# Start and end dates of REX, in YYYY-MM-DD
[dates]
start = "2024-08-25" #Sunday after FPOPs end
end = "2024-08-28"   # Date of FYRE
# Events that start before this hour will be considered as starting the day before in the booklet
hour_cutoff = 4

# List of dorms with REX chair contact emails, available at https://groups.mit.edu/webmoira/list/dorms-rex
[dorms.rex_contact]
"Baker House" = "baker-rush"
"Burton Conner" = "bc-rush"
"East Campus" = "ec-rush-chairs"
"MacGregor House" = "mac-rex-chairs"
"Maseeh Hall" = "maseeh-rex-chairs"
"McCormick Hall" = "mccormick-rex"
"New House" = "nh-rush"
"New Vassar" = "nv-rex-chair"
"Next House" = "next-rex-comm"
"Random Hall" = "random-rush-chair"
"Simmons Hall" = "simmons-frosh-chair"
"DormCon" = "dormcon-rex-chairs"

# List of subdorms in each dorm that equals the main dorm (eg. houses in New House), mainly for contacting REX chairs
[dorms.subdorms]
"Chocolate City" = "New House"
"French House" = "New House"
"German House" = "New House"
"iHouse" = "New House"
"Juniper" = "New House"
"La Casa" = "New House"

# Hardcoding a color for each dorm based on the primary color on their website
[colors.dorms]
"Baker House" = "#005399"
"Burton Conner" = "#cc4331"
"East Campus" = "#aa0000"
"MacGregor House" = "#dc3545"
"Maseeh Hall" = "#1589ff"
"McCormick Hall" = "#293142"
"New House" = "#eaecf9"
"Chocolate City" = "#ffed2e"
"French House" = "#3357cc"
"German House" = "#ff0000"
"iHouse" = "#c78665"
"Juniper" = "#06446c"
"La Casa" = "#e10909"
"New Vassar" = "#afe6af"
"Next House" = "#2c3e50"
"Random Hall" = "#fd5295"
"Simmons Hall" = "#25aae1"
"DormCon" = "#3d93b8"         # DormCon color

[colors.tags]
"tour" = "#34495e"
"signature" = "#f1c40f"
"updated" = "#e67e22"
"food" = "#27ae60"
"party" = "#9b59b6"
"social" = "#e74c3c"
"games" = "#3498db"
"art" = "#1abc9c"

# These control which emoji appear for a tag in the booklet
[tag_emoji]
"food" = "🍴"
"party" = "🎉"
"social" = "👥"
"games" = "🎲"
"art" = "🎨"
