[tool.poetry]
name = "t-rex"
version = "2023.0.0"
description = "A Python project that generates a structured format for REX events and an HTML file that can get converted into a booklet"
authors = ["Cameron Kleiman <ckleiman@mit.edu>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
pytz = "^2023.4"
toml = "^0.10.2"
Jinja2 = "^3.1.3"
markdown = "^3.5"
python-frontmatter = "^1.1.0"

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
