name: Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: '3.10'
      - name: Setup packages
        run: |
          pip install pipenv
          pipenv install
      - name: Process Data
        run: pipenv run python ./process.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: output
          branch: gh-pages
        
        
