name: Build and Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.11'
      - name: Setup packages
        # Skips installing dev dependencies
        run: |
          pip install poetry
          poetry install --only main
      - name: Process Data
        run: poetry run python ./process.py
      - name: Upload result
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: output

  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.1

        
